FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder

COPY . app/
WORKDIR app/
COPY docker/development/appsettings.json .

# get rid of xcopy commands in project files
RUN find . -name \*.csproj -exec sed -i '/<Exec Command="xcopy.*>/d' {} \;
RUN dotnet publish src/Content.WebApi/Content.WebApi.csproj --no-self-contained  --configuration Release -o publish/Content.WebApi --version-suffix local

RUN dotnet publish src/EksEngine/EksEngine.csproj --no-self-contained  --configuration Release -o publish/EksEngine --version-suffix local
RUN dotnet publish src/ManifestEngine/ManifestEngine.csproj --no-self-contained  --configuration Release -o publish/ManifestEngine --version-suffix local
RUN dotnet publish src/Iks.Downloader/Iks.Downloader.csproj --no-self-contained  --configuration Release -o publish/Iks.Downloader --version-suffix local
RUN dotnet publish src/Iks.Uploader/Iks.Uploader.csproj --no-self-contained  --configuration Release -o publish/Iks.Uploader --version-suffix local

RUN find ./publish -name appsettings.json -exec cp appsettings.json {} \;

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
WORKDIR /app
COPY --from=builder app/publish/ .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS="http://*:5000;https://*:5001"
