FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder

COPY . app/
WORKDIR app/
COPY docker/development/appsettings.json .

COPY docker/development/config/appconfig.json .
COPY docker/development/config/riskparams.json .

# get rid of xcopy commands in project files
RUN find . -name \*.csproj -exec sed -i '/<Exec Command="xcopy.*>/d' {} \;
RUN dotnet publish src/DbProvision/DbProvision.csproj --no-self-contained  --configuration Release -o publish --version-suffix local

RUN find ./publish -name appsettings.json -exec cp appsettings.json {} \;

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
WORKDIR /app
COPY --from=builder app/publish/ .
ENTRYPOINT ["dotnet", "DbProvision.dll"]
