FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS builder

COPY . app/
WORKDIR app/
COPY docker/development/appsettings.json .

# get rid of xcopy commands in project files
RUN find . -name \*.csproj -exec sed -i '/<Exec Command="xcopy.*>/d' {} \;
RUN dotnet publish src/DbProvision/DbProvision.csproj --no-self-contained  --configuration Release -o publish --version-suffix local

RUN find ./publish -name appsettings.json -exec cp appsettings.json {} \;

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
WORKDIR /app
COPY --from=builder app/publish/ .
ENTRYPOINT ["dotnet", "DbProvision.dll", "-a", "content/appconfig.json", "-r", "content/riskparams.json", "-b", "content/resourcebundle.json", "-b2", "content/resourcebundlev3.json"]
