CREATE TABLE public.cdn_stats
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    average_daily_users double precision NOT NULL,
    first_date timestamp with time zone NOT NULL,
    last_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_cdn_stats PRIMARY KEY (id)
)
