CREATE TABLE public.dashboard_input_json
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    downloaded_date timestamp with time zone,
    processed_date timestamp with time zone,
    hash text ,
    json_data text,
    CONSTRAINT pk_dashboard_input_json PRIMARY KEY (id)
)

CREATE INDEX ix_dashboard_input_json_hash
    ON public.dashboard_input_json USING btree
    (hash ASC NULLS LAST);
