CREATE TABLE public.dashboard_output_json
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date timestamp with time zone NOT NULL,
    published_date timestamp with time zone,
    json_data text,
    CONSTRAINT pk_dashboard_output_json PRIMARY KEY (id)
)
