// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Efgs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace Eu.Interop {

  /// <summary>Holder for reflection information generated from Efgs.proto</summary>
  public static partial class EfgsReflection {

    #region Descriptor
    /// <summary>File descriptor for Efgs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EfgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFZmdzLnByb3RvEgpldS5pbnRlcm9wIjsKEURpYWdub3Npc0tleUJhdGNo",
            "EiYKBGtleXMYASADKAsyGC5ldS5pbnRlcm9wLkRpYWdub3Npc0tleSL1AQoM",
            "RGlhZ25vc2lzS2V5Eg8KB2tleURhdGEYASABKAwSIgoacm9sbGluZ1N0YXJ0",
            "SW50ZXJ2YWxOdW1iZXIYAiABKA0SFQoNcm9sbGluZ1BlcmlvZBgDIAEoDRId",
            "ChV0cmFuc21pc3Npb25SaXNrTGV2ZWwYBCABKAUSGAoQdmlzaXRlZENvdW50",
            "cmllcxgFIAMoCRIOCgZvcmlnaW4YBiABKAkSKgoKcmVwb3J0VHlwZRgHIAEo",
            "DjIWLmV1LmludGVyb3AuUmVwb3J0VHlwZRIkChxkYXlzX3NpbmNlX29uc2V0",
            "X29mX3N5bXB0b21zGAggASgRKnwKClJlcG9ydFR5cGUSCwoHVU5LTk9XThAA",
            "EhIKDkNPTkZJUk1FRF9URVNUEAESIAocQ09ORklSTUVEX0NMSU5JQ0FMX0RJ",
            "QUdOT1NJUxACEg8KC1NFTEZfUkVQT1JUEAMSDQoJUkVDVVJTSVZFEAQSCwoH",
            "UkVWT0tFRBAFQi8KImV1LmludGVyb3AuZmVkZXJhdGlvbmdhdGV3YXkubW9k",
            "ZWxCCUVmZ3NQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Iks.Protobuf.EfgsReportType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Iks.Protobuf.DiagnosisKeyBatch), global::Iks.Protobuf.DiagnosisKeyBatch.Parser, new[]{ "Keys" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Iks.Protobuf.DiagnosisKey), global::Iks.Protobuf.DiagnosisKey.Parser, new[]{ "KeyData", "RollingStartIntervalNumber", "RollingPeriod", "TransmissionRiskLevel", "VisitedCountries", "Origin", "ReportType", "DaysSinceOnsetOfSymptoms" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums

  #endregion

  #region Messages

  #endregion

}

#endregion Designer generated code
