// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NL.Rijksoverheid.ExposureNotification.BackEnd.Components.EfDatabase.Contexts;

namespace NL.Rijksoverheid.ExposureNotification.BackEnd.Components.Migrations.ExposureContentDbContext
{
    [DbContext(typeof(NL.Rijksoverheid.ExposureNotification.BackEnd.Components.EfDatabase.Contexts.ExposureContentDbContext))]
    [Migration("20200622182046_Field-Updates")]
    partial class FieldUpdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.EntityFrameworkHiLoSequence", "'EntityFrameworkHiLoSequence', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.AppConfig.AppConfigContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignedContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SignedContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishingId")
                        .IsUnique();

                    b.ToTable("AppConfigContent");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.ExposureKeySets.EksCreateJobOutputEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreatingJobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatingJobQualifier")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EksCreateJobOutput");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.ExposureKeySets.ExposureKeySetContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatingJobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatingJobQualifier")
                        .HasColumnType("int");

                    b.Property<string>("PublishingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignedContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SignedContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishingId")
                        .IsUnique();

                    b.ToTable("ExposureKeySetContent");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.ExposureKeySetsEngine.EksCreateJobInputEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("KeyData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RollingPeriod")
                        .HasColumnType("int");

                    b.Property<int>("RollingStartNumber")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionRiskLevel")
                        .HasColumnType("int");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EksCreateJobInput");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.Manifest.ManifestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignedContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SignedContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishingId")
                        .IsUnique();

                    b.ToTable("Manifest");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.ResourceBundle.ResourceBundleContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignedContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SignedContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishingId")
                        .IsUnique();

                    b.ToTable("ResourceBundleContent");
                });

            modelBuilder.Entity("NL.Rijksoverheid.ExposureNotification.BackEnd.Components.RiskCalculationConfig.RiskCalculationContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SignedContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SignedContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishingId")
                        .IsUnique();

                    b.ToTable("RiskCalculationContent");
                });
#pragma warning restore 612, 618
        }
    }
}
