CREATE TABLE public.key_release_workflow_states
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created timestamp with time zone NOT NULL,
    valid_until timestamp with time zone NOT NULL,
    ggd_key character varying(7),
    confirmation_key bytea NOT NULL,
    bucket_id bytea NOT NULL,
    authorised_by_caregiver timestamp with time zone,
    start_date_of_tek_inclusion timestamp with time zone,
    is_symptomatic integer,
    is_origin_portal boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_key_release_workflow_states PRIMARY KEY (id)
);

CREATE INDEX ix_key_release_workflow_states_authorised_by_caregiver
    ON public.key_release_workflow_states USING btree
    (authorised_by_caregiver ASC NULLS LAST);

CREATE INDEX ix_key_release_workflow_states_valid_until
    ON public.key_release_workflow_states USING btree
    (valid_until ASC NULLS LAST);

CREATE UNIQUE INDEX ix_key_release_workflow_states_bucket_id
    ON public.key_release_workflow_states USING btree
    (bucket_id ASC NULLS LAST);

CREATE UNIQUE INDEX ix_key_release_workflow_states_confirmation_key
    ON public.key_release_workflow_states USING btree
    (confirmation_key ASC NULLS LAST);

CREATE UNIQUE INDEX ix_key_release_workflow_states_ggd_key
    ON public.key_release_workflow_states USING btree
    (ggd_key ASC NULLS LAST);
