CREATE TABLE public.diagnosis_keys
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    published_locally boolean NOT NULL,
    daily_key_key_data bytea,
    daily_key_rolling_start_number integer NOT NULL,
    daily_key_rolling_period integer NOT NULL,
    origin integer NOT NULL,
    local_transmission_risk_level integer NOT NULL,
    local_days_since_symptoms_onset integer NOT NULL,
    local_symptomatic integer NOT NULL,
    local_report_type integer NOT NULL,
    published_to_efgs boolean NOT NULL,
    efgs_countries_of_interest text,
    efgs_days_since_symptoms_onset integer,
    efgs_report_type integer,
    efgs_country_of_origin text,
    ready_for_cleanup boolean,
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_diagnosis_keys PRIMARY KEY (id)
);

CREATE INDEX ix_diagnosis_keys_local_symptomatic_local_report_type
    ON public.diagnosis_keys USING btree
    (local_symptomatic ASC NULLS LAST, local_report_type ASC NULLS LAST);