CREATE TABLE public.diagnosis_keys_input
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tek_id bigint NOT NULL,
    daily_key_key_data bytea NOT NULL,
    daily_key_rolling_start_number integer NOT NULL,
    daily_key_rolling_period integer NOT NULL,
    local_transmission_risk_level integer NOT NULL,
    local_days_since_symptoms_onset integer NOT NULL,
    local_symptomatic integer NOT NULL,
    local_report_type integer NOT NULL,
    CONSTRAINT pk_diagnosis_keys_input PRIMARY KEY (id)
);

CREATE INDEX ix_diagnosis_keys_input_tek_id_id
    ON public.diagnosis_keys_input USING btree
    (tek_id ASC NULLS LAST, id ASC NULLS LAST);
