CREATE TABLE public.output
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created timestamp with time zone NOT NULL,
    content bytea NOT NULL,
    creating_job_qualifier integer NOT NULL,
    CONSTRAINT pk_output PRIMARY KEY (id)
);
