CREATE TABLE public.in_job
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    last_batch_tag text,
    last_run timestamp with time zone NOT NULL,
    CONSTRAINT pk_in_job PRIMARY KEY (id)
);
