CREATE TABLE public.received
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    batch_tag text NOT NULL,
    created timestamp with time zone NOT NULL,
    content bytea NOT NULL,
    accepted timestamp with time zone,
    error boolean NOT NULL,
    CONSTRAINT pk_received PRIMARY KEY (id)
);
