CREATE TABLEpublic.eks_output
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    release timestamp with time zone NOT NULL,
    region text NOT NULL,
    content bytea NOT NULL,
    output_id character varying(36),
    creating_job_name text NOT NULL,
    creating_job_qualifier integer NOT NULL,
    CONSTRAINT pk_eks_output PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_eks_output_output_id
    ON public.eks_output USING btree
    (output_id ASC NULLS LAST)
    WHERE output_id IS NOT NULL;
