CREATE TABLE public.eks_input
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tek_id bigint,
    used boolean NOT NULL,
    key_data bytea,
    rolling_start_number integer NOT NULL,
    rolling_period integer NOT NULL,
    transmission_risk_level integer NOT NULL DEFAULT 0,
    days_since_symptoms_onset integer NOT NULL DEFAULT 0,
    symptomatic integer NOT NULL,
    report_type integer NOT NULL DEFAULT 1,
    CONSTRAINT pk_eks_input PRIMARY KEY (id)
);

CREATE INDEX ix_eks_input_key_data
    ON public.eks_input USING btree
    (key_data ASC NULLS LAST);

CREATE INDEX ix_eks_input_transmission_risk_level
    ON public.eks_input USING btree
    (transmission_risk_level ASC NULLS LAST);

CREATE UNIQUE INDEX ix_eks_input_tek_id
    ON public.eks_input USING btree
    (tek_id ASC NULLS LAST);

